<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head
       content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">

  <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css') }}">

  <style>
    .link {
      fill: none;
      stroke: #666;
      stroke-width: 1.5px;
    }
    .node circle {
      fill: #ccc;
      stroke: #fff;
      stroke-width: 1.5px;
    }
    text {
      font: 10px sans-serif;
      pointer-events: none;
    }

    node {
      display: none;
      position: absolute;
      z-index: -1;
    }
  </style>
</head>

<body>



  <script src="{{ url_for('static', filename='assets/js/handlebars.min-latest.js') }}"></script>
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  {% block body %}{% endblock %}

</body>

</html>
